name: Build Containers on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '*/Dockerfile'
      - '*/VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - stn-deploy-2024.1
          - stn-deploy-master
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Read VERSION file
        id: version
        run: echo "::set-output name=version::$(cat ${{ matrix.container }}/VERSION)"
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.container }}
          file: ${{ matrix.container }}/Dockerfile
          load: true # Important: 'load' is set to true instead of 'push'
          tags: ghcr.io/stackers-network/${{ matrix.container }}:${{ steps.version.outputs.version }}
